### PR TITLE
Try to make the program into more normal one

### PR DESCRIPTION
**Pull request by mcepl**
Use Travis CI, setup.py and expressed dependency (instead of bundling a copy of gitshelve).

### CODE REVIEW

**Comment by dgsb** [comment]
Hello,

Beyond making a normal python "a la setuptools", your pull request also remove the capabilities to embed the program in a git repository.
Was that an intended change ?

**Comment by mcepl** [comment]
I don't remember whether it was intended change (it is too long time ago), but I cannot say I am against. I don't think propagating software into data is a good idea.

**Comment by dgsb** [comment]
The file rename prevents an easy merge and the README file as disappeared. Can we first just add the setup.py file ?

**Comment by mcepl** [comment]
If anybody cares about this, they can still find the patch here.

**Pull request closed without merging**
